name: Pipeline Earscope Web

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login Dockerhub
      - name: Login Dockerhub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Extract Tag Git or Commit Hash
      - name: Extract Version from Git Tag or Commit Hash
        id: extract_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            PUSH_LATEST=true
          else
            VERSION="latest"
            PUSH_LATEST=false
          fi
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "push_latest=$PUSH_LATEST" >> $GITHUB_ENV

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/earscopeweb-backend:${{ env.version }} .
          if [[ "${{ env.push_latest }}" == "true" ]]; then
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/earscopeweb-backend:${{ env.version }} \
                       ${{ secrets.DOCKERHUB_USERNAME }}/earscopeweb-backend:latest
          fi

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/earscopeweb-backend:${{ env.version }}
          if [[ "${{ env.push_latest }}" == "true" ]]; then
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/earscopeweb-backend:latest
          fi
